### ISSUE TITLE
Error: Unable to graft xml at selector "/manifest/application" from "/Users/markcl/Projects/wedaycare-client-app-ionic/platforms/android/app/src/main/res/xml/config.xml" during config install

### ISSUE THREAD

**Issue by xmarkclx** [JouriFledderman/cordova-plugin-debuggable-webview#3]
Error: Unable to graft xml at selector "/manifest/application" from "/Users/markcl/Projects/wedaycare-client-app-ionic/platforms/android/app/src/main/res/xml/config.xml" during config install

**Comment by JouriFledderman** [comment]
I can find issues in other plugins with the same error message, which are related to the cordova-android version. For that reason can you post some more information about the ionic, cordova and cordova-android versions that are used in you app?
